[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    'oandapyV20',
    "pandas>=2.3.1",
    'pandas_ta',
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
